/// Arabic letter with glyph, name, transliteration, sound, example word, and dot info.
///
/// Part of the Hoorof (حروف) content ported from raw/hoorof-data.jsx —
/// accuracy preserved exactly: Arabic strings with diacritics, base forms, and dots codes.
class ArabicLetter {
  final String g; // glyph (the letter itself)
  final String nm; // Arabic name (with diacritics)
  final String tr; // transliteration of name
  final String snd; // sound code (phonetic)
  final String w; // example word (Arabic, with diacritics)
  final String wtr; // word transliteration + English gloss
  final String e; // emoji for the word
  final String? base; // dotless base form (for Shape Builder)
  final String? dots; // dots code: '0', or '{count}{a|b}' (above/below)

  const ArabicLetter({
    required this.g,
    required this.nm,
    required this.tr,
    required this.snd,
    required this.w,
    required this.wtr,
    required this.e,
    this.base,
    this.dots,
  });
}

/// All 28 Arabic letters in alphabetical (Abjadi) order.
const List<ArabicLetter> kArabicLetters = [
  ArabicLetter(
    g: 'ا',
    nm: 'أَلِف',
    tr: 'Alif',
    snd: 'a',
    w: 'أَرْنَب',
    wtr: 'arnab (rabbit)',
    e: '🐰',
  ),
  ArabicLetter(
    g: 'ب',
    nm: 'بَاء',
    tr: 'Baa',
    snd: 'b',
    w: 'بَطَّة',
    wtr: 'batta (duck)',
    e: '🦆',
    base: 'ٮ',
    dots: '1b',
  ),
  ArabicLetter(
    g: 'ت',
    nm: 'تَاء',
    tr: 'Taa',
    snd: 't',
    w: 'تُفَّاحَة',
    wtr: 'tuffaha (apple)',
    e: '🍎',
    base: 'ٮ',
    dots: '2a',
  ),
  ArabicLetter(
    g: 'ث',
    nm: 'ثَاء',
    tr: 'Thaa',
    snd: 'th',
    w: 'ثَعْلَب',
    wtr: "tha'lab (fox)",
    e: '🦊',
    base: 'ٮ',
    dots: '3a',
  ),
  ArabicLetter(
    g: 'ج',
    nm: 'جِيم',
    tr: 'Jeem',
    snd: 'j',
    w: 'جَمَل',
    wtr: 'jamal (camel)',
    e: '🐪',
    base: 'ح',
    dots: '1b',
  ),
  ArabicLetter(
    g: 'ح',
    nm: 'حَاء',
    tr: 'Haa',
    snd: 'H',
    w: 'حُوت',
    wtr: 'hoot (whale)',
    e: '🐋',
  ),
  ArabicLetter(
    g: 'خ',
    nm: 'خَاء',
    tr: 'Khaa',
    snd: 'kh',
    w: 'خَرُوف',
    wtr: 'kharoof (sheep)',
    e: '🐑',
    base: 'ح',
    dots: '1a',
  ),
  ArabicLetter(
    g: 'د',
    nm: 'دَال',
    tr: 'Daal',
    snd: 'd',
    w: 'دُبّ',
    wtr: 'dubb (bear)',
    e: '🐻',
  ),
  ArabicLetter(
    g: 'ذ',
    nm: 'ذَال',
    tr: 'Dhaal',
    snd: 'dh',
    w: 'ذِئْب',
    wtr: "dhi'b (wolf)",
    e: '🐺',
    base: 'د',
    dots: '1a',
  ),
  ArabicLetter(
    g: 'ر',
    nm: 'رَاء',
    tr: 'Raa',
    snd: 'r',
    w: 'رِيشَة',
    wtr: 'reesha (feather)',
    e: '🪶',
  ),
  ArabicLetter(
    g: 'ز',
    nm: 'زَاي',
    tr: 'Zaay',
    snd: 'z',
    w: 'زَرَافَة',
    wtr: 'zaraafa (giraffe)',
    e: '🦒',
    base: 'ر',
    dots: '1a',
  ),
  ArabicLetter(
    g: 'س',
    nm: 'سِين',
    tr: 'Seen',
    snd: 's',
    w: 'سَمَكَة',
    wtr: 'samaka (fish)',
    e: '🐟',
  ),
  ArabicLetter(
    g: 'ش',
    nm: 'شِين',
    tr: 'Sheen',
    snd: 'sh',
    w: 'شَمْس',
    wtr: 'shams (sun)',
    e: '☀️',
    base: 'س',
    dots: '3a',
  ),
  ArabicLetter(
    g: 'ص',
    nm: 'صَاد',
    tr: 'Saad',
    snd: 'S',
    w: 'صَقْر',
    wtr: 'saqr (falcon)',
    e: '🦅',
  ),
  ArabicLetter(
    g: 'ض',
    nm: 'ضَاد',
    tr: 'Daad',
    snd: 'D',
    w: 'ضِفْدَع',
    wtr: "dofda' (frog)",
    e: '🐸',
    base: 'ص',
    dots: '1a',
  ),
  ArabicLetter(
    g: 'ط',
    nm: 'طَاء',
    tr: 'Taa',
    snd: 'T',
    w: 'طَائِر',
    wtr: "taa'ir (bird)",
    e: '🐦',
  ),
  ArabicLetter(
    g: 'ظ',
    nm: 'ظَاء',
    tr: 'Zaa',
    snd: 'Z',
    w: 'ظَبْي',
    wtr: 'dhabi (gazelle)',
    e: '🦌',
    base: 'ط',
    dots: '1a',
  ),
  ArabicLetter(
    g: 'ع',
    nm: 'عَيْن',
    tr: 'Ayn',
    snd: 'a3',
    w: 'عِنَب',
    wtr: "'inab (grapes)",
    e: '🍇',
  ),
  ArabicLetter(
    g: 'غ',
    nm: 'غَيْن',
    tr: 'Ghayn',
    snd: 'gh',
    w: 'غُرَاب',
    wtr: 'ghuraab (crow)',
    e: '🐦‍⬛',
    base: 'ع',
    dots: '1a',
  ),
  ArabicLetter(
    g: 'ف',
    nm: 'فَاء',
    tr: 'Faa',
    snd: 'f',
    w: 'فِيل',
    wtr: 'feel (elephant)',
    e: '🐘',
    base: 'ڡ',
    dots: '1a',
  ),
  ArabicLetter(
    g: 'ق',
    nm: 'قَاف',
    tr: 'Qaaf',
    snd: 'q',
    w: 'قِطَّة',
    wtr: 'qitta (cat)',
    e: '🐱',
    base: 'ٯ',
    dots: '2a',
  ),
  ArabicLetter(
    g: 'ك',
    nm: 'كَاف',
    tr: 'Kaaf',
    snd: 'k',
    w: 'كَلْب',
    wtr: 'kalb (dog)',
    e: '🐶',
  ),
  ArabicLetter(
    g: 'ل',
    nm: 'لَام',
    tr: 'Laam',
    snd: 'l',
    w: 'لَيْمُون',
    wtr: 'laymoon (lemon)',
    e: '🍋',
  ),
  ArabicLetter(
    g: 'م',
    nm: 'مِيم',
    tr: 'Meem',
    snd: 'm',
    w: 'مَوْز',
    wtr: 'mawz (banana)',
    e: '🍌',
  ),
  ArabicLetter(
    g: 'ن',
    nm: 'نُون',
    tr: 'Noon',
    snd: 'n',
    w: 'نَحْلَة',
    wtr: 'nahla (bee)',
    e: '🐝',
    base: 'ٮ',
    dots: '1a',
  ),
  ArabicLetter(
    g: 'ه',
    nm: 'هَاء',
    tr: 'Haa',
    snd: 'h',
    w: 'هِلَال',
    wtr: 'hilaal (crescent)',
    e: '🌙',
  ),
  ArabicLetter(
    g: 'و',
    nm: 'وَاو',
    tr: 'Waw',
    snd: 'w',
    w: 'وَرْدَة',
    wtr: 'warda (flower)',
    e: '🌹',
  ),
  ArabicLetter(
    g: 'ي',
    nm: 'يَاء',
    tr: 'Yaa',
    snd: 'y',
    w: 'يَد',
    wtr: 'yad (hand)',
    e: '✋',
    base: 'ى',
    dots: '2b',
  ),
];

/// Confusable letter families for Hear&Match and Shape Builder distractors.
/// Groups of letters that are visually or phonetically similar.
const List<List<String>> kArabicConfusableFamilies = [
  ['ب', 'ت', 'ث', 'ن', 'ي'],
  ['ج', 'ح', 'خ'],
  ['د', 'ذ'],
  ['ر', 'ز'],
  ['س', 'ش'],
  ['ص', 'ض'],
  ['ط', 'ظ'],
  ['ع', 'غ'],
  ['ف', 'ق'],
];

/// Learning clusters: 3–4 letters each, designed for gentle progression.
/// Teaches isolated letter forms in order.
const List<List<String>> kArabicClusters = [
  ['ا', 'ب', 'ت'],
  ['ث', 'ج', 'ح'],
  ['خ', 'د', 'ذ'],
  ['ر', 'ز', 'س'],
  ['ش', 'ص', 'ض'],
  ['ط', 'ظ', 'ع'],
  ['غ', 'ف', 'ق'],
  ['ك', 'ل', 'م'],
  ['ن', 'ه', 'و', 'ي'],
];
