import 'dart:math';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:wonder_quest/features/parent/parent_gate.dart';

/// Computes the deterministic first question generated by [Random(seed)].
///
/// Mirrors the generation logic in [_ParentGateDialogState._generateQuestion]:
///   a = 3 + random.nextInt(7)
///   b = 3 + random.nextInt(7)
({int a, int b}) _firstQuestion(int seed) {
  final rng = Random(seed);
  final a = 3 + rng.nextInt(7);
  final b = 3 + rng.nextInt(7);
  return (a: a, b: b);
}

void main() {
  group('showParentGate', () {
    testWidgets('correct product resolves true and closes dialog',
        (tester) async {
      // Determine the deterministic question from seed 1.
      final q = _firstQuestion(1);
      final productStr = (q.a * q.b).toString();

      bool? result;

      await tester.pumpWidget(
        MaterialApp(
          home: Builder(
            builder: (ctx) => GestureDetector(
              key: const Key('open-gate'),
              onTap: () {
                showParentGate(ctx, random: Random(1)).then((r) {
                  result = r;
                });
              },
              child: const Text('Open'),
            ),
          ),
        ),
      );

      // Open the gate.
      await tester.tap(find.byKey(const Key('open-gate')));
      await tester.pumpAndSettle();

      // Dialog must be visible.
      expect(find.byKey(const Key('gate-dialog')), findsOneWidget);

      // Enter each digit of the correct product.
      for (final digit in productStr.split('')) {
        await tester.tap(find.byKey(Key('gate-digit-$digit')));
        await tester.pump();
      }

      // Tap the check button.
      await tester.tap(find.byKey(const Key('gate-check')));
      await tester.pumpAndSettle();

      // Dialog must be gone and result must be true.
      expect(find.byKey(const Key('gate-dialog')), findsNothing);
      expect(result, isTrue);
    });

    testWidgets('wrong entry keeps dialog open', (tester) async {
      bool? result;

      await tester.pumpWidget(
        MaterialApp(
          home: Builder(
            builder: (ctx) => GestureDetector(
              key: const Key('open-gate'),
              onTap: () {
                showParentGate(ctx, random: Random(1)).then((r) {
                  result = r;
                });
              },
              child: const Text('Open'),
            ),
          ),
        ),
      );

      // Open the gate.
      await tester.tap(find.byKey(const Key('open-gate')));
      await tester.pumpAndSettle();

      expect(find.byKey(const Key('gate-dialog')), findsOneWidget);

      // Enter '1' — always wrong (min product is 3×3=9).
      await tester.tap(find.byKey(const Key('gate-digit-1')));
      await tester.pump();

      // Tap check — wrong answer triggers shake + new question.
      await tester.tap(find.byKey(const Key('gate-check')));
      await tester.pumpAndSettle();

      // Dialog stays open, no result yet.
      expect(find.byKey(const Key('gate-dialog')), findsOneWidget);
      expect(result, isNull);
    });

    testWidgets('dismiss with X returns false', (tester) async {
      bool? result;

      await tester.pumpWidget(
        MaterialApp(
          home: Builder(
            builder: (ctx) => GestureDetector(
              key: const Key('open-gate'),
              onTap: () {
                showParentGate(ctx, random: Random(1)).then((r) {
                  result = r;
                });
              },
              child: const Text('Open'),
            ),
          ),
        ),
      );

      await tester.tap(find.byKey(const Key('open-gate')));
      await tester.pumpAndSettle();

      expect(find.byKey(const Key('gate-dialog')), findsOneWidget);

      // Tap ✕ to dismiss.
      await tester.tap(find.byKey(const Key('gate-close')));
      await tester.pumpAndSettle();

      expect(find.byKey(const Key('gate-dialog')), findsNothing);
      expect(result, isFalse);
    });
  });
}
